pipeline {
    agent none

    stages {
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.9.9-amazoncoretto-21'
                    args '-u root'
                }
            }

            steps {
                withCredentials([
                    file(credentialsId: 'hase-backend-private-key', variable: 'PRIVATE_KEY'),
                    file(credentialsId: 'hase-backend-public-key', variable: 'PUBLIC_KEY')
                ]) {
                dir('backend') {
                    sh 'mkdir src/main/resources/certs'
                    dir('src/main/resources/certs') {
                            sh 'cp $PRIVATE_KEY private.pem'
                            sh 'cp $PUBLIC_KEY public.pem'
                    }

                    sh 'mvn clean test'
                }
            }
        }
    }
}