pipeline {
    agent none

    stages {
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.9.9-eclipse-temurin-21-noble'
                    args '-u root'
                }
            }

            steps {
                dir('backend') {
                    sh 'mvn clean test'
                }
            }
        }
    }
}
