/*
 * This file is generated by jOOQ.
 */
package database.tables.records;


import database.tables.Appointments;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppointmentsRecord extends UpdatableRecordImpl<AppointmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Appointments.appointmentId</code>.
     */
    public void setAppointmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Appointments.appointmentId</code>.
     */
    public Integer getAppointmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Appointments.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Appointments.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Appointments.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>Appointments.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>Appointments.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Appointments.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppointmentsRecord
     */
    public AppointmentsRecord() {
        super(Appointments.APPOINTMENTS);
    }

    /**
     * Create a detached, initialised AppointmentsRecord
     */
    public AppointmentsRecord(Integer appointmentid, String name, LocalDateTime date, String location) {
        super(Appointments.APPOINTMENTS);

        setAppointmentid(appointmentid);
        setName(name);
        setDate(date);
        setLocation(location);
        resetChangedOnNotNull();
    }
}
