/*
 * This file is generated by jOOQ.
 */
package de.hase.hasev2.database.tables.records;


import de.hase.hasev2.database.tables.Participates;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ParticipatesRecord extends UpdatableRecordImpl<ParticipatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>participates.appointmentId</code>.
     */
    public void setAppointmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>participates.appointmentId</code>.
     */
    public Integer getAppointmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>participates.matrikelNr</code>.
     */
    public void setMatrikelnr(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>participates.matrikelNr</code>.
     */
    public Integer getMatrikelnr() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipatesRecord
     */
    public ParticipatesRecord() {
        super(Participates.PARTICIPATES);
    }

    /**
     * Create a detached, initialised ParticipatesRecord
     */
    public ParticipatesRecord(Integer appointmentid, Integer matrikelnr) {
        super(Participates.PARTICIPATES);

        setAppointmentid(appointmentid);
        setMatrikelnr(matrikelnr);
        resetChangedOnNotNull();
    }
}
