/*
 * This file is generated by jOOQ.
 */
package de.hase.hasev2.database.tables.records;


import de.hase.hasev2.database.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Users.matrikelNr</code>.
     */
    public void setMatrikelnr(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Users.matrikelNr</code>.
     */
    public Integer getMatrikelnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Users.firstName</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Users.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Users.lastName</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Users.lastName</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Users.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Users.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer matrikelnr, String firstname, String lastname, String email) {
        super(Users.USERS);

        setMatrikelnr(matrikelnr);
        setFirstname(firstname);
        setLastname(lastname);
        setEmail(email);
        resetChangedOnNotNull();
    }
}
