/*
 * This file is generated by jOOQ.
 */
package de.hase.hasev2.database;


import de.hase.hasev2.database.tables.Appointments;
import de.hase.hasev2.database.tables.Participates;
import de.hase.hasev2.database.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>Appointments</code>.
     */
    public final Appointments APPOINTMENTS = Appointments.APPOINTMENTS;

    /**
     * The table <code>participates</code>.
     */
    public final Participates PARTICIPATES = Participates.PARTICIPATES;

    /**
     * The table <code>Users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Appointments.APPOINTMENTS,
            Participates.PARTICIPATES,
            Users.USERS
        );
    }
}
