/*
 * This file is generated by jOOQ.
 */
package de.hase.hasev2.database;


import de.hase.hasev2.database.tables.Appointments;
import de.hase.hasev2.database.tables.records.AppointmentsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppointmentsRecord> APPOINTMENTS__PK_APPOINTMENTS = Internal.createUniqueKey(Appointments.APPOINTMENTS, DSL.name("pk_Appointments"), new TableField[] { Appointments.APPOINTMENTS.APPOINTMENTID }, true);
}
