/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.Appointments;
import database.tables.Users;
import database.tables.records.AppointmentsRecord;
import database.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppointmentsRecord> APPOINTMENTS__PK_APPOINTMENTS = Internal.createUniqueKey(Appointments.APPOINTMENTS, DSL.name("pk_Appointments"), new TableField[] { Appointments.APPOINTMENTS.APPOINTMENTID }, true);
    public static final UniqueKey<UsersRecord> USERS__PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] { Users.USERS.MATRIKELNR }, true);
}
