/*
 * This file is generated by jOOQ.
 */
package de.hase.hasev2.database;


import de.hase.hasev2.database.tables.Appointments;
import de.hase.hasev2.database.tables.Participates;
import de.hase.hasev2.database.tables.Users;
import de.hase.hasev2.database.tables.records.AppointmentsRecord;
import de.hase.hasev2.database.tables.records.ParticipatesRecord;
import de.hase.hasev2.database.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppointmentsRecord> APPOINTMENTS__PK_APPOINTMENTS = Internal.createUniqueKey(Appointments.APPOINTMENTS, DSL.name("pk_Appointments"), new TableField[] { Appointments.APPOINTMENTS.APPOINTMENTID }, true);
    public static final UniqueKey<ParticipatesRecord> PARTICIPATES__PK_PARTICIPATES = Internal.createUniqueKey(Participates.PARTICIPATES, DSL.name("pk_participates"), new TableField[] { Participates.PARTICIPATES.APPOINTMENTID, Participates.PARTICIPATES.MATRIKELNR }, true);
    public static final UniqueKey<UsersRecord> USERS__PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_Users"), new TableField[] { Users.USERS.MATRIKELNR }, true);
    public static final UniqueKey<UsersRecord> USERS__UK_USERS_1_45170427 = Internal.createUniqueKey(Users.USERS, DSL.name("uk_Users_1_45170427"), new TableField[] { Users.USERS.EMAIL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppointmentsRecord, UsersRecord> APPOINTMENTS__FK_APPOINTMENTS_PK_USERS = Internal.createForeignKey(Appointments.APPOINTMENTS, DSL.name("fk_Appointments_pk_Users"), new TableField[] { Appointments.APPOINTMENTS.CREATOR }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.MATRIKELNR }, true);
    public static final ForeignKey<ParticipatesRecord, AppointmentsRecord> PARTICIPATES__FK_PARTICIPATES_PK_APPOINTMENTS = Internal.createForeignKey(Participates.PARTICIPATES, DSL.name("fk_participates_pk_Appointments"), new TableField[] { Participates.PARTICIPATES.APPOINTMENTID }, Keys.APPOINTMENTS__PK_APPOINTMENTS, new TableField[] { Appointments.APPOINTMENTS.APPOINTMENTID }, true);
    public static final ForeignKey<ParticipatesRecord, UsersRecord> PARTICIPATES__FK_PARTICIPATES_PK_USERS = Internal.createForeignKey(Participates.PARTICIPATES, DSL.name("fk_participates_pk_Users"), new TableField[] { Participates.PARTICIPATES.MATRIKELNR }, Keys.USERS__PK_USERS, new TableField[] { Users.USERS.MATRIKELNR }, true);
}
