/*
 * This file is generated by jOOQ.
 */
package de.hase.hasev2.database;


import de.hase.hasev2.database.tables.Appointments;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>Appointments</code>.
     */
    public static final Appointments APPOINTMENTS = Appointments.APPOINTMENTS;
}
