name: E2E Tests
on: push

jobs:
    test:
        name: Run end to end tests
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up RSA Keys
                run: |
                  mkdir backend/src/main/resources/certs
                  echo "${{ secrets.RSA_PRIVATE_KEY }}" >> backend/src/main/resources/certs/private.pem
                  echo "${{ secrets.RSA_PUBLIC_KEY }}" >> backend/src/main/resources/certs/public.pem
                  chmod 600 backend/src/main/resources/certs/private.pem
                  chmod 644 backend/src/main/resources/certs/public.pem

            -   name: Set up JDK and Maven cache
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: 'maven'

            -   name: Build backend
                run: mvn -f backend/pom.xml clean install

            -   name: Run backend
                run: java -jar backend/target/hasev2-*.jar &

            -   name: Waiting for backend to be ready
                run: |
                    echo "Waiting for backend to start..."
                    while ! curl -sSf http://localhost:8080/health; do
                        echo "Waiting for backend to start"
                        sleep 5
                    done

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '22'

            -   name: Install dependencies
                run: npm install -g yarn && yarn install --frozen lockfile
                working-directory: frontend
                

            -   name: Install playwright browser dependencies
                run: yarn playwright install --with-deps
                working-directory: frontend

            -   name: Build frontend
                run: npm run build
                working-directory: frontend

            -   name: Run e2e tests
                run: npm run test:e2e
                working-directory: frontend
                
            -   uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: playwright-report
                    path: frontend/test-results
                    retention-days: 30
