name: Backend Unit Tests
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up RSA Keys
        run: |
          mkdir backend/src/main/resources/certs
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > backend/src/main/resources/certs/private.pem
          echo "${{ secrets.RSA_PUBLIC_KEY }}" > backend/src/main/resources/certs/public.pem
          chmod 600 private.pem
          chmod 644 public.pem

      - name: Set up JDK and Maven cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn -f backend/pom.xml clean test
