name: Frontend Unit Tests
on: push

jobs:
    test:
        name: Run end to end tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up RSA Keys
                run: |
                  echo "${{ secrets.RSA_PRIVATE_KEY }}" > backend/src/main/resources/certs/private.pem
                  echo "${{ secrets.RSA_PUBLIC_KEY }}" > backend/src/main/resources/certs/public.pem
                  chmod 600 private.pem
                  chmod 644 public.pem

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '22'

            -   name: Install dependencies
                run: npm install -g yarn && yarn install --frozen lockfile
                working-directory: frontend

            -   name: Run tests
                run: npm run test:unit
                working-directory: frontend
