name: Frontend Unit Tests
on: push

jobs:
    test:
        name: Run end to end tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '22'

            -   name: Install dependencies
                run: npm install -g yarn && yarn install --frozen lockfile
                working-directory: frontend

            -   name: Run tests
                run: npm run test:unit
                working-directory: frontend
